config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save

    flash[:notice] = @bookmark.errors.full_messages.to_sentence unless @bookmark.save

    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list =  List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
      <div class="logo navbar-brand">
        <%= image_tag "logo.jpg", alt: "Logo", class: "rounded-circle"%>
      </div>
      <div>
        <%= link_to "My Lists", lists_path %> |
        <%= link_to "New List", new_list_path %>
      </div>
    </div>

      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="home-banner">
    <h1><span id="banner-typed-text"></span></h1>
</div>

<div class="container" style="margin-top: 50px;">
  <div class="d-flex justify-content-between">
    <h2 class="list-banner">My lists</h2>
    <%= link_to "Create a movie list", new_list_path, class:"btn btn-success"  %>
  </div>

  <div class="d-flex flex-wrap my-4">
    <% @lists.each do |list|%>
      <div class="card d-inline-flex justify-content-between  mx-2" style="width:18rem">
      <%= link_to list.name, list_path(list.id), class: "card-body text-center text-nowrap"%>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container" style="margin-top: 120px;">
  <h1 class="list-banner">New List</h1>

  <%= simple_form_for [ @list ] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs mt-4">
    <%= f.input :name %>
    </div>
    <div class="form-actions mb-4">
    <%= f.submit "Create list", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container" style="margin-top: 120px;">
  <h2 class=list-banner><%= @list.name %></h2>
  <% @list.bookmarks.each do |bookmark| %>
  <div class="card d-inline-flex mt-5" style="width: 18rem;">
    <%= image_tag bookmark.movie.poster_url, alt: "", class:"card-img-top" %>
    <div class="card-body">
        <p class="card-title font-weight-bold"><%= bookmark.movie.title %> | <%= bookmark.movie.rating %> 🖤</p>

      <p class="card-text"><%= bookmark.movie.overview %></p>
      <div class="d-flex justify-content-between">
        <p><i class="fas fa-quote-left"></i> <%= bookmark.comment %></p>
        <%= link_to "Delete",
                    list_bookmark_path(list_id: @list, id:bookmark.id),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs mt-4">
      <%= f.association :movie %>
      <%= f.input :comment %>
    </div>

    <div class="form-actions mb-4">
    <%= f.button :submit, class:"btn btn-success"%>
    </div>
  <% end %>
</div>